### PR TITLE
use androidx.biometrics to support devices since android 6

### PR DESCRIPTION
**Pull request by ksc91u**
Thanks for the review, I create a new pull request to keep original for reference.

Changes I made:

1. lateinit disposable will be uninitialized and cause crash if button not pushed and put activity to back.
2. hasBiometrics support now does not check android version, only check fingerprint support
3. AuthenticationCallback in androidx support library only has three methods, success, fail, error. Help message now include in fail message.
4. Now require an activity to bring up fingerprint, if activity onPause, fingerprint dialog will automatically be cancelled.

### CODE REVIEW

**Comment by pwittchen** [comment]
Thanks for the updated PR. It looks much better than PR #8. I'll analyze and test it. If everything will be fine, then I'll merge it.

**Comment by ksc91u** [comment]
By the way, the original MainActivity in app-kotlin calls RxBiometric with IO scheduler with `.subscribeOn(Schedulers.io())` . It crash on my Sony XZ Android O.

That is why I try switch it back to UI thread in RxBiometric.authenticate.

**Comment by pwittchen** [comment]
It's strange. Maybe it's a phone issue? I tested it on the Pixel 2 and it worked fine. AFAIK there should be a possibility to test it on Android emulator too.

**Comment by ksc91u** [comment]
I don't know why it happen, since I set a break point in Biometric framework to ensure I got mainExecutor.
My Pixel 3 also won't crash, but Genymotion does crash

**Comment by chiinau** [comment]
Any progress on this pull request?

**Comment by pwittchen** [comment]
I'll try to take care of it soon. Recently, I didn't have time for that.

**Comment by ksc91u** [comment]
There are issues with androidx.biometrics alpha 3.

https://issuetracker.google.com/issues/122929952

Before those issues fixed, you may not want to use androidx.biometrics in your production environment.

**Comment by pwittchen** [comment]
I tested it on Android 9 (Pie) and Google Pixel 2 and it worked fine. Update will be available in the next release. In case of problems with androidx, users can always fall-back to the previous version of the library.

**Pull request merged**
