### PR TITLE
adding AuthenticatorTypes

### PR DESCRIPTION
**Pull request by bagbyte**
You have been too quick :)
Can you release a new version of the package as well?

### CODE REVIEW

**Review by pwittchen — APPROVED** [review]

**Comment by pwittchen** [comment]
Sure.

**Comment by bagbyte** [comment]
@pwittchen  I find out the hasBiometricSupport needs some change...you may want to wait before releasing a new version

**Comment by pwittchen** [comment]
I'll test it before the release and verify it it's working at least on my phone. I'm not sure if this can be tested on emulator. If something will be wrong, then I'll rollback changes.

**Comment by bagbyte** [comment]
hasBiometricSupport is currently available only for API 23, and it checks only for `FEATURE_FINGERPRINT` (leaving `FEATURE_FACE` and `FEATURE_IRIS` out), would be better to use `BiometricManager.canAuthenticate` which takes care of wrapping the logic based on the running SDK

**Comment by pwittchen** [comment]
Ok, I'll check it. If you want to update this, new PRs are welcome.

pon., 31 maj 2021, 15:05 użytkownik Sabino ***@***.***>
napisał:

**Pull request merged**
